/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author aaron
 */
public class MainMenuFrame extends javax.swing.JFrame {
    private Library library = new Library(); 
    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuFrame() {
        initComponents();
        library.loadBooks();
        CardLayout cl = (CardLayout)jPanel3.getLayout();
        cl.show(jPanel3, "card7"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        homePane1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addPane1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        authorField = new javax.swing.JTextField();
        isbnLabel = new javax.swing.JLabel();
        isbnField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox<>();
        pagesLabel = new javax.swing.JLabel();
        pagesField = new javax.swing.JTextField();
        sizeLabel = new javax.swing.JLabel();
        sizeField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        listPane1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTextArea = new javax.swing.JTextArea();
        refreshBtn = new javax.swing.JButton();
        searchTitlePane1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        searchTitleField = new javax.swing.JTextField();
        searchTitleBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchTitleTextArea = new javax.swing.JTextArea();
        searchAuthorPane1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchAuthorField = new javax.swing.JTextField();
        searchAuthorBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchAuthorTextArea = new javax.swing.JTextArea();
        removePane1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        removeList = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        removeConfirmBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Book");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("List All Books");
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setBackground(new java.awt.Color(153, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Search by Title");
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Search by Author");
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(153, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Remove Book");
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton6.setBackground(new java.awt.Color(153, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Save & Exit");
        jButton6.setFocusPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel3.setLayout(new java.awt.CardLayout());

        homePane1.setBackground(new java.awt.Color(51, 51, 51));
        homePane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 211, 211)), "Welcome to your Library Management System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Select an option above");

        javax.swing.GroupLayout homePane1Layout = new javax.swing.GroupLayout(homePane1);
        homePane1.setLayout(homePane1Layout);
        homePane1Layout.setHorizontalGroup(
            homePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePane1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        homePane1Layout.setVerticalGroup(
            homePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePane1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jPanel3.add(homePane1, "card7");

        addPane1.setBackground(new java.awt.Color(153, 0, 0));
        addPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 211, 211)), "Enter details of the book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        addPane1.setForeground(new java.awt.Color(255, 255, 255));

        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Enter Title: ");

        titleField.setBackground(new java.awt.Color(51, 51, 51));
        titleField.setForeground(new java.awt.Color(255, 255, 255));
        titleField.setPreferredSize(new java.awt.Dimension(150, 26));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Author: ");

        authorField.setBackground(new java.awt.Color(51, 51, 51));
        authorField.setForeground(new java.awt.Color(255, 255, 255));
        authorField.setPreferredSize(new java.awt.Dimension(150, 26));

        isbnLabel.setForeground(new java.awt.Color(255, 255, 255));
        isbnLabel.setText("Enter ISBN: ");

        isbnField.setBackground(new java.awt.Color(51, 51, 51));
        isbnField.setForeground(new java.awt.Color(255, 255, 255));
        isbnField.setPreferredSize(new java.awt.Dimension(150, 26));

        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setText("Select Type: ");

        typeBox.setBackground(new java.awt.Color(153, 153, 153));
        typeBox.setForeground(new java.awt.Color(255, 255, 255));
        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Printed", "eBook" }));

        pagesLabel.setForeground(new java.awt.Color(255, 255, 255));
        pagesLabel.setText("Enter Pages: ");

        pagesField.setBackground(new java.awt.Color(51, 51, 51));
        pagesField.setForeground(new java.awt.Color(255, 255, 255));
        pagesField.setPreferredSize(new java.awt.Dimension(50, 26));

        sizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        sizeLabel.setText("Enter Size (MB): ");

        sizeField.setBackground(new java.awt.Color(51, 51, 51));
        sizeField.setForeground(new java.awt.Color(255, 255, 255));
        sizeField.setPreferredSize(new java.awt.Dimension(50, 26));

        saveBtn.setBackground(new java.awt.Color(51, 51, 51));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save Book");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPane1Layout = new javax.swing.GroupLayout(addPane1);
        addPane1.setLayout(addPane1Layout);
        addPane1Layout.setHorizontalGroup(
            addPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPane1Layout.createSequentialGroup()
                .addGroup(addPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPane1Layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPane1Layout.createSequentialGroup()
                        .addComponent(isbnLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isbnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPane1Layout.createSequentialGroup()
                        .addGroup(addPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addComponent(pagesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pagesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPane1Layout.createSequentialGroup()
                        .addComponent(sizeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 483, Short.MAX_VALUE))
            .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addPane1Layout.setVerticalGroup(
            addPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(authorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnLabel)
                    .addComponent(isbnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagesLabel)
                    .addComponent(pagesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeLabel)
                    .addComponent(sizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn))
        );

        jPanel3.add(addPane1, "card2");

        listPane1.setBackground(new java.awt.Color(153, 0, 0));
        listPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 211, 211)), "All books in the library", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        listPane1.setLayout(new java.awt.BorderLayout());

        listTextArea.setBackground(new java.awt.Color(102, 102, 102));
        listTextArea.setColumns(40);
        listTextArea.setForeground(new java.awt.Color(255, 255, 255));
        listTextArea.setLineWrap(true);
        listTextArea.setRows(15);
        listTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(listTextArea);

        listPane1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        refreshBtn.setBackground(new java.awt.Color(51, 51, 51));
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        listPane1.add(refreshBtn, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(listPane1, "listPane1");

        searchTitlePane1.setBackground(new java.awt.Color(153, 0, 0));
        searchTitlePane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 211, 211)), "Search by Title", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        searchTitlePane1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Title contains: ");
        jPanel4.add(jLabel2);

        searchTitleField.setBackground(new java.awt.Color(51, 51, 51));
        searchTitleField.setColumns(20);
        searchTitleField.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(searchTitleField);

        searchTitlePane1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        searchTitleBtn.setBackground(new java.awt.Color(51, 51, 51));
        searchTitleBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchTitleBtn.setText("Search");
        searchTitleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTitleBtnActionPerformed(evt);
            }
        });
        searchTitlePane1.add(searchTitleBtn, java.awt.BorderLayout.PAGE_END);

        searchTitleTextArea.setEditable(false);
        searchTitleTextArea.setBackground(new java.awt.Color(102, 102, 102));
        searchTitleTextArea.setColumns(40);
        searchTitleTextArea.setForeground(new java.awt.Color(255, 255, 255));
        searchTitleTextArea.setRows(10);
        jScrollPane2.setViewportView(searchTitleTextArea);

        searchTitlePane1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.add(searchTitlePane1, "card4");

        searchAuthorPane1.setBackground(new java.awt.Color(153, 0, 0));
        searchAuthorPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 211, 211)), "Search by Author", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        searchAuthorPane1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Author contains: ");

        searchAuthorField.setBackground(new java.awt.Color(51, 51, 51));
        searchAuthorField.setColumns(40);
        searchAuthorField.setForeground(new java.awt.Color(255, 255, 255));
        searchAuthorField.setPreferredSize(new java.awt.Dimension(454, 26));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 161, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(searchAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchAuthorPane1.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        searchAuthorBtn.setBackground(new java.awt.Color(51, 51, 51));
        searchAuthorBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchAuthorBtn.setText("Search");
        searchAuthorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAuthorBtnActionPerformed(evt);
            }
        });
        searchAuthorPane1.add(searchAuthorBtn, java.awt.BorderLayout.PAGE_END);

        searchAuthorTextArea.setEditable(false);
        searchAuthorTextArea.setBackground(new java.awt.Color(102, 102, 102));
        searchAuthorTextArea.setColumns(20);
        searchAuthorTextArea.setForeground(new java.awt.Color(255, 255, 255));
        searchAuthorTextArea.setRows(5);
        jScrollPane3.setViewportView(searchAuthorTextArea);

        searchAuthorPane1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel3.add(searchAuthorPane1, "card5");

        removePane1.setBackground(new java.awt.Color(153, 0, 0));
        removePane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(211, 211, 211)), "Remove books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        removePane1.setLayout(new java.awt.BorderLayout());

        removeList.setBackground(new java.awt.Color(102, 102, 102));
        removeList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select books to remove", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        removeList.setForeground(new java.awt.Color(255, 255, 255));
        removeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(removeList);

        removePane1.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(153, 0, 0));

        removeConfirmBtn.setBackground(new java.awt.Color(51, 51, 51));
        removeConfirmBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeConfirmBtn.setText("Remove");
        removeConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeConfirmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removeConfirmBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(removeConfirmBtn))
        );

        removePane1.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(removePane1, "card6");

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel3.getLayout();
        cl.show(jPanel3, "listPane1"); 
        
        listTextArea.setText(library.retrieveAllBooks()); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        listTextArea.setText(library.retrieveAllBooks()); 
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String title = titleField.getText();
        String author = authorField.getText();
        String isbn = isbnField.getText();
        
       if(typeBox.getSelectedItem().equals("Printed")){
           int pages = Integer.parseInt(pagesField.getText());
           library.addBook(new PrintedBook(title, author, isbn, pages));
           }else{
           double size = Double.parseDouble(sizeField.getText());
           library.addBook(new eBook(title,author,isbn,size));
           
       }
       JOptionPane.showMessageDialog(this, "Book added to library.");
       titleField.setText("");
       authorField.setText("");
       isbnField.setText("");
       pagesField.setText("");
       sizeField.setText("");   
    }//GEN-LAST:event_saveBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel3.getLayout();
        cl.show(jPanel3, "card2");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchTitleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTitleBtnActionPerformed
        // TODO add your handling code here:
        String term = searchTitleField.getText();
        searchTitleTextArea.setText(library.retrieveBookByTitle(term));
    }//GEN-LAST:event_searchTitleBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel3.getLayout();
        cl.show(jPanel3, "card4");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchAuthorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAuthorBtnActionPerformed
        // TODO add your handling code here:
        String words = searchAuthorField.getText();
        searchAuthorTextArea.setText(library.retrieveBookByAuthor(words));
    }//GEN-LAST:event_searchAuthorBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel3.getLayout();
        cl.show(jPanel3, "card5");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel3.getLayout();
        cl.show(jPanel3, "card6"); 
        
    Book[] books = library.getBooks();
    String[] display = new String[books.length];
    for (int i = 0; i < books.length; i++) {
        display[i] = books[i].toString();
    }
    removeList.setListData(display);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void removeConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeConfirmBtnActionPerformed
        // TODO add your handling code here:
        int idx = removeList.getSelectedIndex();
        if (idx >= 0) {
        Book selectedBook = library.getBooks()[idx];
        library.removeBook(selectedBook);

        Book[] books = library.getBooks();
        String[] display = new String[books.length];
        for (int i = 0; i < books.length; i++) {
            display[i] = books[i].toString();
        }
        
        removeList.setListData(display);

        JOptionPane.showMessageDialog(this, "Removed: " + selectedBook);
    } else {
        JOptionPane.showMessageDialog(this, "Please select a book first.", "No Selection", JOptionPane.WARNING_MESSAGE);
    }
        
    }//GEN-LAST:event_removeConfirmBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        library.saveBooks();
        library.saveBooksToCSV();
        System.exit(0); 
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuFrame().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPane1;
    private javax.swing.JTextField authorField;
    private javax.swing.JPanel homePane1;
    private javax.swing.JTextField isbnField;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel listPane1;
    private javax.swing.JTextArea listTextArea;
    private javax.swing.JTextField pagesField;
    private javax.swing.JLabel pagesLabel;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton removeConfirmBtn;
    private javax.swing.JList<String> removeList;
    private javax.swing.JPanel removePane1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchAuthorBtn;
    private javax.swing.JTextField searchAuthorField;
    private javax.swing.JPanel searchAuthorPane1;
    private javax.swing.JTextArea searchAuthorTextArea;
    private javax.swing.JButton searchTitleBtn;
    private javax.swing.JTextField searchTitleField;
    private javax.swing.JPanel searchTitlePane1;
    private javax.swing.JTextArea searchTitleTextArea;
    private javax.swing.JTextField sizeField;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> typeBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
